edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = false
format_code_in_doc_comments = false
comment_width = 80
match_arm_leading_pipes = "Never"
